services:
  mcp_client:
    build:
      context: ./mcp_client
      dockerfile: Dockerfile
    image: mcp_client_img:latest
    container_name: mcp_client_container
    env_file:
      - ./mcp_client/.env