# for devcontainer
services:
  mcp_client:
    build:
      target: devcontainers
      context: ./mcp_client
      dockerfile: Dockerfile
    image: mcp_client_image_devcontainer:latest
    container_name: mcp_client_devcontainer
    volumes:
      - ./:/app
